---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: stock-lakehouse
spec:
  selector:
    app: kafka
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: stock-lakehouse
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: stock-lakehouse
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: stock-lakehouse
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
